name: flutter_application_todo_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_local_notifications: ^18.0.1
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - images/image.jpg

flutter_native_splash:
  android: true
  ios: true
  color: "#ffffff"
  image: "images/image.jpg"